# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region       = "us-east-1"
  default_tags {
    tags = {"Env":"Personal","ManualBuild":false,"ManualTag":false,"Owner":"rodmans","Region":"us-east-1"}
  }
}
