# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "aws-rstuhlmuller-s3-usw2"
    dynamodb_table = "terraform-state-lock"
    encrypt        = true
    key            = "IaC/my_website/prod/us-west-2/ui/terraform.tfstate"
    region         = "us-west-2"
  }
}
