# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region       = "us-west-2"
  default_tags {
    tags = {"Env":"Personal","ManualBuild":false,"ManualTag":false,"Owner":"rodmans","Region":"us-west-2"}
  }
}
