---
name: 'Infracost'

on:
    pull_request:
        branches:
            - main

jobs:
    infracost:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            # Required to post comments
            pull-requests: write
        steps:
            - name: Setup Infracost
              uses: infracost/actions/setup@v2
              # See https://github.com/infracost/actions/tree/master/setup for other inputs
              # If you can't use this action, see Docker images in https://infracost.io/cicd
              with:
                api-key: ${{ secrets.INFRACOST_API_KEY }}

            - name: Checkout base branch
              uses: actions/checkout@v3
              with:
                ref: '${{ github.event.pull_request.base.ref }}'

            - name: Generate Infracost cost estimate baseline
              run: |
                infracost breakdown --path=${TF_ROOT} \
                                    --format=json \
                                    --out-file=/tmp/infracost-base.json

            - name: Checkout PR branch
              uses: actions/checkout@v3

            - name: Generate Infracost diff
              run: |
                infracost diff --path=${TF_ROOT} \
                                --format=json \
                                --compare-to=/tmp/infracost-base.json \
                                --out-file=/tmp/infracost.json

            - name: Post Infracost comment
              run: |
                infracost comment github --path=/tmp/infracost.json \
                                            --repo=$GITHUB_REPOSITORY \
                                            --github-token=${{github.token}} \
                                            --pull-request=${{github.event.pull_request.number}} \
                                            --behavior=update