---
name: 'Check PR title and commit log messages'

on:
  push:

jobs:
  terraform-plan:
    defaults:
      run:
        working-directory: ./IaC
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout
    steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v2
          with:
            aws-region: us-west-2
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

        - name: Terraform Plan
          uses: rstuhlmuller/terraform-action-cicd/.github/actions/terraform-plan@main
          with:
            working-directory: ./IaC