---
name: 'Check PR title and commit log messages'

on:
  push:

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v2
          with:
            role-to-assume: arn:aws:iam::716182248480:role/Rodman_Stuhlmuller_Net-Site
            role-session-name: terraform-plan-my_website
            aws-region: us-west-2

        - name: cd tf
          run: |    
            cd IaC

        - name: Terraform Plan
          uses: rstuhlmuller/terraform-action-cicd/.github/actions/terraform-plan@main